### ISSUE TITLE
Build Task Errors

### ISSUE THREAD

**Issue by Tattedgeek** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#26]
# Module: 4
#### Step: 00

Description of issue
BuildTask errors occur but nothing can be fixed.

Repro steps:
![image](https://user-images.githubusercontent.com/31896372/174491374-874e3f0b-c017-43fb-9996-3929f832fda8.png)

**Comment by janeteblake** [comment]
I'm guessing that you did not complete the prerequisites.

The prerequisites are impossible because Xtreme (I'm assuming you're using an Xtreme machine?) did not populate the course assets:
![image](https://user-images.githubusercontent.com/54034556/175650042-629e5966-4b9b-4c31-a035-9f2ddad3485f.png)

Please report to Xtreme, and I will too.
Thank you.

Closing as it's not a lab issue, but a VM one.

**Comment by janeteblake** [comment]
p.s. I could not report it to Xtreme, as I could not provide a page number. If you could do so, that would be helpful.

**Comment by Tattedgeek** [comment]
Will do.

Brent
