### ISSUE TITLE
Lab 1: "An unexpected client error has occurred", Finance and Operations page unresponsive

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#73]
- Learning Path 01: Introduction to developing with finance and operations apps
- Lab 1: Create a new module
- Exercise 2: Create a new module
- Task 7: Test

&

- Optional exercise 5: Add a list in the Tabbed List Section
- Task 4: Test

We have received reports of the below error message appearing on the Finance and Operations page after refreshing per the tasks referenced above. On closing the message dialog, the page UI is found to be largely unresponsive.

> An unexpected client error has occurred

![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/134323425/3159efcf-3471-4fab-bc4a-a626aeb5e724)

Refreshing the page or rebooting the server virtual machine does not clear the error or resolve the unresponsive page state.

We have not determined a reliable method of triggering this error message in a new lab session. Exercise 2 referenced above was successfully completed in our tests thus far. The repeated observations of this issue by instructors remain unexplained and of concern.

**Comment by janeteblake** [comment]
Dear Skillable, might I suggest you try clearing usage data in your base client machines? Top right gear > User options > Usage data > Reset [Unexpected client side errors keep popping up in D365 Finance & Operations - Help / Activities - UiPath Community Forum](https://forum.uipath.com/t/unexpected-client-side-errors-keep-popping-up-in-d365-finance-operations/352974)

Also, you might check the event viewer, if you can, on the machines it’s reported on. 

Other forums blame software added. What might have been added to these VMs since engineering released?

I hope this research has been helpful, but if not, an issue can always be reported on Lifecycle Services.

Regards,
Janet

**Comment by SkillableMG** [comment]
Thank you for the reply, Janet. 

Regarding the usage data reset, that was attempted within affected instances of the lab. However, the unresponsive state of the page prevented that action from being initiated.

Our review of the event log on affected VMs did not immediately reveal relevant entries. Any suggestions of specific messages to look for would be appreciated.

I am not aware of additional software added to the VM, but will consult internally in case more info is available.

**Comment by janeteblake** [comment]
When it happens, can you open a second window to attempt the usage data reset? 

I'll start up a VM tomorrow to get the exact application name to filter the event viewer by.

**Comment by janeteblake** [comment]
I looked up the Event Viewer. I think it would most likely be in **Windows Logs** > **Application**, an Error level with a source of Dynamics something, perhaps **Dynamics Server DynamicsAXBatchManagement**.  
![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/54034556/7eaa62fa-2e8f-4300-9d02-3b1ac67d73a2)

If that doesn't help, the best way is still to open an issue on Lifecycle Services. But if you cannot do that, have George ask his engineering contacts what to do.
